version: '3.8'

services:
  vue:
    container_name: vue
    build:
      context: .
      dockerfile: vue.dockerfile
    tty: true
    privileged: true
    stdin_open: true
    volumes:
        - ./app:/app
    ports:
        - 9000:9000
    command: /bin/sh
